<a href="https://colab.research.google.com/github/sumitgaikwad8877/python-Question/blob/main/python_partice_Q.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#What is the output of the following?

x = 'abcd'
for i in range(len(x)):
     x[i].upper()
print (x)

abcd


In [ ]:
x = 50
def func():
     global x
     print('x is', x)
     x = 2
     print('Changed global x to', x)
func()
print('Value of x is', x)

x is 50
Changed global x to 2
Value of x is 2


In [ ]:

import numpy as np

dt = np.dtype([('age',np.int8)])

a = np.array([(10,),(20,),(30,)], dtype = dt)

print (a['age'])

[10 20 30]


In [ ]:
a = [5,5,6,7,7,7]
b = set(a)
def test(lst):
     if lst in b:
        return 1
     else:
        return 0
for i in filter(test, a):
     print(i,end=" ")

5 5 6 7 7 7 

In [ ]:
arr = [3 , 2 , 5 , 6 , 0 , 7, 9]
add1 = 0
add2 = 0
for elem in arr:
    if (elem % 1 == 0):
       add1 = add1 + elem
       continue
    if (elem % 3 == 0):
       add2 = add2 + elem
print(add1 , end=" ")
print(add2)

32 0


In [ ]:
flag = ""
a = 0
i = 1
while(a < 3):
    j = 1
    if flag:
       i = j * i + 5
    else:
       i = j * i + 1
       a = a + 1
print(i)

4


In [ ]:

l1=[1, 2, 3, [4]]
l2=list(l1)
id(l1)==id(l2)


False

In [ ]:
import pandas as pd
import numpy as np
s = pd.Series(np.random.randn(4))
print( s.ndim)

1


In [ ]:
import numpy as np
a = np.array([1, 2, 3,4,5], ndmin = 2)
print (a)

[[1 2 3 4 5]]


In [ ]:
 # Q1.reversing a string
 x = input('string:')
 y = x[::-1]
print(y)

string:Sumit
timuS


In [ ]:

A = input()
def revers_string(A):
  return A[::-1]
print(revers_string(A))

Sumit
timuS


In [1]:
a= input()
def polindarama(a):
  if a[::-1] == a[::]:
    return "pol"
  else:
    return "Not"
print(polindarama(a))

1123112
Not


In [ ]:
 x =input("Enter string:")
 y = x [::-1].upper()
 print(y)

Enter string:sumit
TIMUS


In [ ]:
 # revarseing string use lower() funtion
 x = input('string:')
 y = x[::-1].lower()
print(y)

string:Sumit
timus


In [ ]:
x = input('string: ')
y = x[::-1]
if y == x:
  print('y')

string: sbjwnd


In [ ]:
# how to remove spaces from a string in pyhton?

A = input('Enter u r string')
print(A.replace(" ",""))

Enter u r stringsumit gaikwad
sumitgaikwad


In [ ]:
q = input()
def removespace(q):
  return q.replace(" ","")
print(removespace(q))

s u m i t
sumit


In [ ]:
A = input()
def repl_space(A):
  return A.replace(" ","")
print(repl_space(A))

Sumit gaikwad
Sumitgaikwad


In [ ]:
a = input()
def revs_(a):
  return a[::-1]
print(revs_(a))

Sumit
timuS


In [ ]:
A = input()
def relc_space(A):
  return A.replace(" ","")
print(relc_space(A))

sumit gaikwad 
sumitgaikwad


In [ ]:
# Q.2Python Program to Check whether Year is a Leap Year or not
# User enters the year
year = int(input("Enter Year: "))

# Leap Year Check
if year % 5 == 0 and year % 100 != 0:
    print(year, "is a Leap Year")
elif year % 100 == 0:
    print(year, "is not a Leap Year")
elif year % 400 ==0:
    print(year, "is a Leap Year")
else:
    print(year, "is not a Leap Year")

Enter Year: 1996
1996 is not a Leap Year


In [ ]:
year = int(input())
def leap_year(year):
  if year % 4 == 0:
    return 'leap'
  else:
    return 'Not'
print(leap_year(year))

2000
leap


In [ ]:
y = int(input())
def leap_year(y):
  if y % 4 == 0:
    return 'its leap year'
  else:
    return 'Not leap year'
print(leap_year(y))

1998
Not leap year


In [ ]:
year = int(input())
def leap_year(year):
  if year % 4 == 0:
    return 'leap year'
  else:
    return 'Not'
print(leap_year(year))

2000
leap year


HackerRanK problem 

In [41]:
n = int(input().strip())
for i in range(1, n + 1):
    print(i, end='')


3
123

Task 2: Shape and Reshape
You are given a space separated list of nine integers. Your task is to convert this list into a X NumPy array.

Input Format

A single line of input containing space separated integers.

Output Format

Print the X NumPy array.

Sample Input

1 2 3 4 5 6 7 8 9

Sample Output

[ [ 1 2 3 ]

[ 4 5 6 ]

[ 7 8 9 ] ]

In [57]:


import numpy

def arrays(arr):
    arr1 = numpy.array(arr, dtype = int)
    arr2 = arr1.reshape(3, 3)
    return arr2

arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


 Transpose and Flatten
You are given a N X M integer array matrix with space separated elements (N = rows and M = columns). Your task is to print the transpose and flatten results.

Input Format

The first line contains the space separated values of N and M. The next lines contains the space separated elements of M columns.

Output Format

First, print the transpose array and then print the flatten.

Sample Input

2 2

1 2

3 4

Sample Output

[[1 3]

[2 4]]

[1 2 3 4]

In [58]:
import numpy

n, m = map(int, input().split())
array = numpy.array([input().strip().split() for _ in range(n)], int)
print (array.transpose())
print (array.flatten())

2 2
1 3
4 4
[[1 4]
 [3 4]]
[1 3 4 4]


In [48]:
import numpy

my_array = numpy.array([9,8,7,6,5,4,3,2,1])
X = numpy.reshape(my_array,(3,3))
print(X)



[[9 8 7]
 [6 5 4]
 [3 2 1]]


 Concatenate
You are given two integer arrays of size N X P and M X P (N & M are rows, and P is the column). Your task is to concatenate the arrays along axis 0.

Input Format

The first line contains space separated integers N, M and P. The next N lines contains the space separated elements of the P columns. After that, the next M lines contains the space separated elements of the P columns.

Output Format

Print the concatenated array of size (N+M)XP.

Sample Input

4 3 2

1 2

1 2

1 2

1 2

3 4

3 4

3 4

Sample Output

[[1 2]

[1 2]

[1 2]

[1 2]

[3 4]

[3 4]

[3 4]]

In [59]:
import numpy

X, Y, Z = map(int, input().split())
array = numpy.array([input().split() for i in range(X+Y)], int)

print(array)

4 3 2
1 2
1 2
 1 2
  1 2
3 4
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


Zeros and Ones
You are given the shape of the array in the form of space-separated integers, each integer representing the size of different dimensions, your task is to print an array of the given shape and integer type using the tools numpy.zeros and numpy.ones.

Input Format

A single line containing the space-separated integers.

Output Format

First, print the array using the numpy.zeros tool and then print the array with the numpy.ones tool.

Sample Input 0

3 3 3

Sample Output 0

[[[0 0 0]

[0 0 0]

[0 0 0]]

[[0 0 0]

[0 0 0]

[0 0 0]]

[[0 0 0]

[0 0 0]

[0 0 0]]]

[[[1 1 1]

[1 1 1]

[1 1 1]]

[[1 1 1]

[1 1 1]

[1 1 1]]

[[1 1 1]

[1 1 1]

[1 1 1]]]

In [60]:
# to be frank there is only one part that I got the solution for, that is how to return multiple values. And the logic part is mine.
# https://www.geeksforgeeks.org/g-fact-41-multiple-return-values-in-python/

import numpy

def arrays(arr):
    arr1 = numpy.array(arr, dtype = int)
    arr2 = numpy.zeros(arr1, dtype = int)
    arr3 = numpy.ones(arr1, dtype = int)
    return arr2, arr3

arr = input().strip().split(' ')
arr2, arr3 = arrays(arr)

print(arr2)
print(arr3)

3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


In [ ]:
# leap year or Not

year = int(input())
def leapyear_Not(year):
  if year % 4 == 0:
    return 'leap year'
  else:
    return 'Not leap year'
print(leapyear_Not(year))


1998
Not leap year


*  Leap year mean 366 day in a year
Feb 29 ki jiss year me hoti h wo leap year hoti h

In [ ]:
# Q3.range porgaram
x = int(input())
if x in range(1,100):
   print(" this no less than 100")
elif x in range(99,100):
     print("same")
else:
  print("more than 100") 

20
 this no less than 100


In [ ]:
x = input('x=')
if x in range(2,6):
  print("weird")
elif x in range(6,16):
  print("not weird")
else:
  print('out of range')

x=3
out of range


In [ ]:
# print first 5 integers
# using python range() function
for i in range(5,100,5):
    print(i, end=" ")
print()

5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95 


In [ ]:
for i in range (2,20,2):
  print(i, end = " ")
print()

2 4 6 8 10 12 14 16 18 


In [ ]:
# Q 3.The isupper() method returns True if all the characters are in upper case, otherwise False. Numbers, symbols and spaces are not checked, only alphabet characters
x = "sumit"
x.isupper()

False

In [ ]:
y = "SUMIT"
y[0:3].isupper()
     

True

In [ ]:
# Amstrong number
num = int(input("enter a num: "))
x= num
sum = 0
while x>0:
  y = x%10
  sum += y**2
  x//=10
  if num == sum:
    print(num,"is an Armstring number")
  else:
    print(num,"is not a Armstrong number")

enter a num: 5
5 is not a Armstrong number


In [ ]:
x = int(input())
num = x
def amstor(num):
  a = num%10
  num = num //10
  b = num %10
  c = num //10
  if (a**3)+(b**3)+(c**3) == x:
    return 'ams'
  else:
    return 'Not'
print(amstor(x))

153
ams


In [ ]:
y = int(input())
num = y
def asmsto(num):
  a = num %10
  num = num//10
  b = num % 10
  c = num//10
  if (a**3) + (b**3) +(c**3) == y:
    return "ams"
  else:
    return "Not"
print(asmsto(y))

153
ams


In [ ]:
x =int(input())
num= x
def amsto(num):
  a = num % 10
  num = num//10
  b = num %10
  c = num //10
  if (a**3)+(b**3)+(c**3) == x:
    return "amsto"
  else :
    return ' Not'
print(amsto(x))

153
amsto


In [ ]:
a = int(input())
k = a
b = len(str(a))
sum = 0
while a > 0:
  digit = a%10
  sum += digit**b
  a = a//10
if k == sum :
  print("this is")
else:
  print("Not") 

153
this is


In [ ]:
# Python program to check if the number is an Armstrong number or not

# take input from the user
num = int(input("Enter a number: "))

# initialize sum
sum = 0

# find the sum of the cube of each digit
temp = num
while temp > 0:
   digit = temp % 10
   sum += digit ** 3
   temp //= 10

# display the result
if num == sum:
   print(num,"is an Armstrong number")
else:
   print(num,"is not an Armstrong number")


Enter a number: 153
153 is an Armstrong number


In [ ]:
# python porgaram to display all prime numbers within an interval
lower=10
upper = 100

print("prime numbers betwwen", lower, "and", upper,"are:")

for num in range(lower, upper +1):
  # all prime numbers are greater than 1

  if num >1:
    for i in range(2, num):
      if (num%i) == 0:
          break
    else:
      print(num)

    

prime numbers betwwen 10 and 100 are:
11
13
17
19
23
29
31
37
41
43
47
53
59
61
67
71
73
79
83
89
97


In [ ]:
xyz = [1,4,5,1,2,3,45]
xyz[0],xyz[-1]=xyz[-1],xyz[0]
print(xyz)

[45, 4, 5, 1, 2, 3, 1]


In [ ]:
#In this specific example, the input is a list of numbers. And we have to return the mean and median of this list of numbers
# calculate mean & median
def calculate_averages(my_list):
  '''
  This function calculates the mean and median of a given list of numbers.
  '''
  # Step 1 : Calculate the mean
  mean = sum(my_list)/len(my_list)

  # Step 2 : Calculate the median
  sorted_list = sorted(my_list)
  list_length = len(sorted_list)

  if list_length%2 == 0:
    median = (sorted_list[int(list_length/2)-1] + sorted_list[int(list_length/2)])/2
  else :
    median = sorted_list[int((list_length+1)/2) - 1]
     
  return  mean, median

In [ ]:
heights =  [172,175,170,168,170,200]
calculate_averages(heights)

TypeError: ignored

In [ ]:
# Let us write a function with multiple return statements
# check_even_or_odd(num) porgaram
num = int(input())
def xyz(num):
  if num%2 == 0:
    return 'even'
  else:
    return 'odd'
print(xyz(num))

2
even


In [ ]:
x = int(input())
def even_odd_num(x):
  if x %2 == 0:
    return "even"
  else:
    return 'odd'
print(even_odd_num(x))

5
odd


In [ ]:
num = int (input())
def sss(num):
  if num % 2 == 0:
    return 'Even'
  else:
    return ' odd'
print(sss(num))

5
 odd


In [ ]:
num = int(input())
def sss(num):
  if num %2 == 0:
    return "even"
  else:
    return "odd"
print(sss(num))

7
odd


## <b> Almax <B>

In [ ]:
# Q1.python program to remove empty list from the main list
A = [5,4,6,81,[],[],12,2,54]
B = [x for x in A if x]
print(B)

[5, 4, 6, 81, 12, 2, 54]


In [ ]:
A = [5,4,6,81,[],[],12,2,54]
def remove_elist(A):
  return [x for x in A if x]
print(remove_elist(A))

[5, 4, 6, 81, 12, 2, 54]


In [ ]:
def remove_dupl(lis):
  return list(set(lis))


In [ ]:
B = [1,1,2,4,3,42,4,]
print(remove_dupl(B))

[1, 2, 3, 4, 42]


In [ ]:
A = [5,4,6,81,[],[],12,2,54]
def E_list_remove(A):
  return [x for x in A if x]
print(E_list_remove(A))


[5, 4, 6, 81, 12, 2, 54]


In [ ]:
 s = [1,5,3,4,[],[],1,5]
 d = [ x for x in s if x]
 print(d)


[1, 5, 3, 4, 1, 5]


In [ ]:
A = [5,4,6,81,[],[],12,2,54]

def removeemptylist(lis):
  return [x for x in A if x]
print(A)
print(removeemptylist(A))

[5, 4, 6, 81, [], [], 12, 2, 54]
[5, 4, 6, 81, 12, 2, 54]


In [ ]:
input_list = [5, 6, [], 3, [], [], 9]
input_list2 = [x for x in input_list if x]
print(input_list2)

[5, 6, 3, 9]


In [ ]:
# Python Code to Remove empty List from List

def empty_list_remove(input_list):
	new_list = []
	for ele in input_list:
		if ele:
			new_list.append(ele)
	return new_list


# input list values
input_list = [5, 6, [], 3, [], [], 9]

# print initial list values
print(f"The original list is : {input_list}")
# function-call & print values
print(f"List after empty list removal : {empty_list_remove(input_list)}")


The original list is : [5, 6, [], 3, [], [], 9]
List after empty list removal : [5, 6, 3, 9]


In [ ]:
def empty(s):
  a = []
  for x in s:
    if x:
      a.append(x)
  return a

  s =[5, 6, [], 3, [], [], 9]
print(empty(s))

[1, 5, 3, 4, 1, 5]


In [ ]:
L = [1,2,3,4,[],5,6]
h =  [ x for x in L if x]
print(h)
  

[1, 2, 3, 4, 5, 6]


Q2.different parts of syntax of list comprehension

* As per the above syntax, the list comprehension syntax contains three parts: an expression, one or more for loop, and optionally, one or more if conditions. The list comprehension must be in the square brackets [] . The result of the first expression will be stored in the new list.

Q3. When do you a boxplot and in waht situation would you choose boxplot over histogaram and wat if formeting could you gain from a box-polt

Ans -Histograms are preferred to determine the underlying probability distribution of a data. Box plots on the other hand are more useful when comparing between several data sets. They are less detailed than histograms and take up less space.

Histograms and box plots are very similar in that they both help to visualize and describe numeric data. Although histograms are better in determining the underlying distribution of the data, box plots allow you to compare multiple data sets better than histograms as they are less detailed and take up less space.

In [ ]:
#Q.4 find the second largest number in List
# using sort() funtion
L = [1,2,3,5,46,8,95,]
L.sort()
print(L[-2])

46


In [ ]:
L = [1,2,3,5,46,8,95,]
L.sort()
print(L[-3])

8


In [ ]:
L = [1,2,3,5,46,8,95,]
L1 = set(L)
L1.remove(max(L1))
print(max(L1))

46


In [ ]:
# using remove/max funtion
L = [1,2,3,5,46,8,95,]
L1=set(L)
L1.remove(max(L1))

print(max(L1))


Q5. difference between collaborative and content based recommender systems
* Ans-Content-based filtering does not require other users' data during recommendations to one user. Collaborative filtering System: Collaborative does not need the features of the items to be given. Every user and item is described by a feature vector or embedding. It creates embedding for both users and items on its own
* Content-based filtering uses similarities in products, services, or content features, as well as information accumulated about the user to make recommendations. Collaborative filtering relies on the preferences of similar users to offer recommendatio

In [ ]:
# Q.6 Reverse the integer 1234(do not change type the data)
num = 1234
reversed_num = 0

while num !=0:
  digit=num%10
  reversed_num=reversed_num *10 + digit
  num//=10
print("Reverse Number:" + str(reversed_num))

Reverse Number:4321


In [ ]:
a = int(input('number: '))
rv = 0
while a != 0:
   digit = a%10
   rv = rv*10 + digit
   a = a//10
print(rv)

number: 12345
54321


In [ ]:
A = int(input())
rv = 0
while A != 0:
  dig = A %10
  rv = rv *10 +dig
  A = A//10
print(rv)

12345
54321


In [ ]:
d = int(input())
rvs= 0
while d != 0:
  digs = d%10
  rvs = rvs*10+digs
  d = d//10
print(rvs)

123
321


In [ ]:
ss = int(input('Enter number:'))
rv = 0
while ss != 0:
  digits = ss%10
  rv = rv*10 + digits
  ss = ss//10
print(rv)

Enter number:123456789
987654321


In [ ]:
aa = int(input('Enter num:'))
rv = 0
while aa != 0:
  dig = aa%10
  rv = rv*10 + dig
  aa = aa //10
print(rv) 

Enter num:12345
54321


In [ ]:
 G = int(input('number:'))
 s = 0
 while G != 0:
   D = G%10
   s = s*10 + D
   G = G//10
print(s)

number:12345
54321


In [ ]:
A = int(input())
rv = 0
while A != 0:
  d = A%10
  rv = rv*10 +d
  A = A//10
print(rv)

12345
54321


In [ ]:
num = int(input())
def rev_int(num):
  return (str(num))[::-1]
print(rev_int(num))

12345
54321


In [ ]:
num = 1234
print(str(num)[::-1])

4321


In [ ]:
n = 123456789
print(str(n)[::-1])

987654321


In [ ]:
# Q.7 How to drop from a DataFrame
# import pandas pakage
# create a dictionary with five filed each
import pandas as pd
data = {
    'A': ['A1', 'A2', 'A3', 'A4', 'A5'],
    'B': ['B1', 'B2', 'B3', 'B4', 'B5'],
    'C': ['C1', 'C2', 'C3', 'C4', 'C5'],
    'D': ['D1', 'D2', 'D3', 'D4', 'D5'],
    'E': ['E1', 'E2', 'E3', 'E4', 'E5']}
print(data)
    


{'A': ['A1', 'A2', 'A3', 'A4', 'A5'], 'B': ['B1', 'B2', 'B3', 'B4', 'B5'], 'C': ['C1', 'C2', 'C3', 'C4', 'C5'], 'D': ['D1', 'D2', 'D3', 'D4', 'D5'], 'E': ['E1', 'E2', 'E3', 'E4', 'E5']}


In [ ]:
# covert the dictionary into Dataframe
df = pd.DataFrame(data)
df

A   B   C   D   E
0  A1  B1  C1  D1  E1
1  A2  B2  C2  D2  E2
2  A3  B3  C3  D3  E3
3  A4  B4  C4  D4  E4
4  A5  B5  C5  D5  E5

In [ ]:
# remove column name "A"
df.drop(["A"],axis=1)

B   C   D   E
0  B1  C1  D1  E1
1  B2  C2  D2  E2
2  B3  C3  D3  E3
3  B4  C4  D4  E4
4  B5  C5  D5  E5

In [ ]:
import pandas as pd
data = {
    'A' :[1,2,3,45,6],
    'B':[4,5,6,7,8],
    'C':[5,7,8,6,4],
    'D':[44,5,2,88,5]
}
print(data)


{'A': [1, 2, 3, 45, 6], 'B': [4, 5, 6, 7, 8], 'C': [5, 7, 8, 6, 4], 'D': [44, 5, 2, 88, 5]}


In [ ]:
df = pd.DataFrame(data)
df


A  B  C   D
0   1  4  5  44
1   2  5  7   5
2   3  6  8   2
3  45  7  6  88
4   6  8  4   5

In [ ]:
df.dropna(inplace= True)
df= df[df.A!=2]
df

/usr/local/lib/python3.8/dist-packages/pandas/util/_decorators.py:311: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return func(*args, **kwargs)


A  B  C   D
2   3  6  8   2
3  45  7  6  88
4   6  8  4   5

Q.8 what is interquartile range
* Ans. The interquartile range (IQR) is the difference between the 75th and 25th percentile of the data. It is a measure of the dispersion similar to standard deviation or variance, but is much more robust against outliers [2

* The interquartile range (IQR) contains the second and third quartiles, or the middle half of your data set. Whereas the range gives you the spread of the whole data set, the interquartile range gives you the range of the middle half of a data set

In [ ]:
# Q.9 Given a list write a python porgaram to swap frist and last element of list
my = [5, 6, 7, 10, 11, 12]
my[0],my[-1] =my[-1],my[0]
print(my)


[12, 6, 7, 10, 11, 5]


In [ ]:
y = [5, 6, 7, 10, 11, 12]
y[0],y[-1] = y[-1],y[0]
print(y)


[12, 6, 7, 10, 11, 5]


In [ ]:
def swap_fun(s_list):
  swap =  s_list[0],s_list[-1] = s_list[-1],s_list[0]
  return s_list
y = [5, 6, 7, 10, 11, 12]
print(swap_fun(y))

[12, 6, 7, 10, 11, 5]


In [ ]:

def swap_func(sample_list):
  size = len(sample_list)

#swap logic
  temp = sample_list[0]
  sample_list[0] = sample_list[size -1]
  sample_list[size -1] = temp
  return sample_list


In [ ]:
y = [5, 6, 7, 10, 11, 12]
print(swap_func(y))

[12, 6, 7, 10, 11, 5]


In [ ]:
mylist   = [5, 6, 7, 10, 11, 12]
first_el = mylist.pop(0)   # first_el = 5, mylist = [6, 7, 10, 11, 12]
last_el  = mylist.pop(-1)  # last_el = 12, mylist = [6, 7, 10, 11]
mylist.insert(0, last_el)  # mylist = [12, 6, 7, 10, 11]
mylist.append(first_el)    # mylist = [12, 6, 7, 10, 11, 5]
mylist

[12, 6, 7, 10, 11, 5]

In [ ]:
#list[0], list[-1] = list[-1], list[0]
xyz = [1,4,5,1,2,3,45]
xyz[0],xyz[-1]=xyz[-1],xyz[0]
print(xyz)

[45, 4, 5, 1, 2, 3, 1]


Q10.what is aggregate function

* Ans--The aggregate() method allows you to apply a function or a list of function names to be executed along one of the axis of the DataFrame, default 0, which is the index (row) axis. Note: the agg() method is an alias of the aggregate() method.

* An aggregate function is a mathematical computation involving a range of values that results in just a single value expressing the significance of the accumulated data it is derived from. Aggregate functions are often used to derive descriptive statistics.

Q11.Which all python libraries have you used for visualization

* Ans--Matplotlib and Seaborn are python libraries that are used for data visualization. They have inbuilt modules for plotting different graphs. While Matplotlib is used to embed graphs into applications, Seaborn is primarily used for statistical graphs

Q.12 how can we visualize more than three dimensions of data in a single chart
* Ans--The best way to go higher than three dimensions is to use plot facets, color, shapes, sizes, depth and so on. You can also use time as a dimension by making an animated plot for other attributes over time (considering time is a dimension in the data)

Q.13 What are important features of a good data visualization?
* Here are 10 elements of good data visualization that can help you present information that readers can process quickly and easily.
Clear Headings and Keys. ...
Obvious Trends. ...
Simple Analysis. ...
Relevant Comparisons. ...
Lots of Data/Evidence. ...
Summaries of Key Points. ...
Add design elements. ...
Consolidated Information.

In [ ]:
# Q14.write a function to find the words in a string that greater than the given number
n="hello geeks for geeks is computer science portal"; l=3
s = n.split(" ")
l = list(filter(lambda x: (len(x)>l),s))
print(l)


['hello', 'geeks', 'geeks', 'computer', 'science', 'portal']


In [ ]:
s = " sumit son of rameshwar gaikwad"
l = 3
a = [x for x in s.split() if len(x)>l]
print(a)

['sumit', 'rameshwar', 'gaikwad']


In [ ]:
sentence = "hello geeks for geeks is computer science portal"
length = 4
s=sentence.split()
print([a for i,a in enumerate(s) if len(a) > length])

['hello', 'geeks', 'geeks', 'computer', 'science', 'portal']


In [ ]:
sentence = "hello geeks for geeks is computer science portal"
length = 4
print([word for word in sentence.split() if len(word) > length])


['hello', 'geeks', 'geeks', 'computer', 'science', 'portal']


In [ ]:
s = "hello geeks for geeks is computer science portal"
L = 4
sa = [x for x in s.split() if len(x) < L]
print(sa)

['for', 'is']


In [ ]:
# that ok 
sentence = "hello geeks for geeks is computer science portal"
length = 4
ss = [ x for x in sentence.split() if len(x) > length]
print(ss)

['hello', 'geeks', 'geeks', 'computer', 'science', 'portal']


In [ ]:
def word_k(k,s):
  word = s.split(" ")
  for x in word:
    if len(x)>k:
      print(x)
k =3
s="hello geeks for geeks is computer science portal"
print(word_k(k,s))


hello
geeks
geeks
computer
science
portal
None


In [ ]:
s="hello geeks for geeks is computer science portal";L=4
A=s.split(" ")
L= list(filter(lambda x: (len(x)>L),A))
print(L)


['hello', 'geeks', 'geeks', 'computer', 'science', 'portal']


In [ ]:
s="hello geeks for geeks is computer science portal";L=4
A = s.split(" ")
L = list(filter(lambda x :(len(x)>L),A))
print(L)

['hello', 'geeks', 'geeks', 'computer', 'science', 'portal']


In [ ]:
# Q.16 Write a python porgaram to find all odd number in given range
S = int(input())
E = int(input())
for x in range(S, E + 1):
  if x % 2 != 0:
    print(x)


1
10
1
3
5
7
9


In [ ]:
first_num = int(input("Enter frist num:"))
second_num = int(input('Enter secound num:'))

for x in range(first_num,second_num):
  if x % 2 != 0:
    print(x)


Enter frist num:1
Enter secound num:10
1
3
5
7
9


Q 17.what are the different names for rows and columns in a dataframe

* Ans--Pandas Dataframe type has two attributes called 'columns' and 'index' which can be used to change the column names as well as the row indexes.

Q.18 what is the major difference between for loop and while loop
* The for and while loops are both conditional statements. A for loop is a single-line command that will be executed repeatedly. While loops can be single-lined or contain multiple commands for a single condition. Both the for loop and the while loop are important in computer languages for obtaining results.

In [ ]:
# Q.19 write a program for factorial in python
# Recursion is the concept where a funtion can call itself any number of tiomes that a certain condition is met
# The conditions is important to avoid infinite loops

def factorial(a):
  if a == 1:
    return 1
  else:
    return(a*factorial(a-1))
input_num = 5
print("the fact of",input_num,'is',factorial(input_num))




the fact of 5 is 120


In [ ]:
num = int(input('Enter the number:'))
def factorial(num):
  if num == 1 :
    return 1
  else:
    return (num*factorial(num-1))
print(factorial(num))

Enter the number:5
120


In [ ]:
num = int(input())
def fact(num):
  if num == 1:
    return 1
  else:
    return (num*fact(num-1))
print(fact(num))

5
120


In [ ]:
x = int(input())
def factorial(x):
  if x == 1:
    return 1
  else:
    return (x*factorial(x-1))
print(factorial(x))

5
120


In [ ]:
num = int(input('Enter the number:'))
def factorial(num):
  if num == 1 :
    return 1
  else:
    return(num*factorial (num -1))
print('this fact:', factorial(num))

Enter the number:5
this fact: 120


In [ ]:
def xyz(b):
    if b==1:
        return 1
    else:
        return(b*xyz(b-1))
num = 5

print(xyz(num))

120


In [ ]:
sss=int(input())
def xyz(b):
    if b==1:
        return 1
    else:
        return(b*xyz(b-1))

print(xyz(num))

5
120


In [ ]:
ss=int(input())
def factorial(q):
  if q==1:
      return 1
  else:
    return (q*factorial(q-1))
print(factorial(num))

5
120


In [ ]:
# using numpy
import numpy as np
n = 5
x = np.prod([i for i in range(1,n+1)])
print(x)

120


In [ ]:
import numpy as np
n=int(input())
x = np.prod([i for i in range(1,n+1)])
print(x)

5
120


In [ ]:
#Q20.Python3 Program to find sum of square of first n natural numbers Return the sum of square of first natural numbers

def squaresum(n) :
	return (n * (n + 1) * (2 * n + 1)) // 6

# Driven Program
n = 6
print(squaresum(n))



91


In [ ]:
num = int(input())
def sq(num):
  return (num *(num +1) * (2 * num + 1)) //6
print(sq(num))

5
55


In [ ]:
# Python3 Program to find sum of square of first n natural numbers
# Return the sum of square of first nnatural numbers
def squaresum(n) :

	sm = 0
	for i in range(1, n+1) :
		sm = sm + (i * i)
	
	return sm

# Driven Program
n = 6
print(squaresum(n))



91


In [ ]:
x = int(input())
def squaresum(x):
  y = 0
  for i in range(1,x+1):
    y = y + ( i * i )
  return y
print(squaresum(x))


6
91


In [ ]:
num = int(input())
def sq(num):
  s = 0
  for i in range(1,num+1):
    s = s +( i * i)
  return s
print(sq(num))

5
55


In [ ]:
num = int(input())
def xyz(num):
  s = 0
  for i in range(1,num+1):
    s = s+(i * i)
  return s
print(xyz(num))


5
55


In [ ]:
sum = int(input())
def qqq(sum):
  r = 0
  for i in range(1,sum+1):
    r = r+(i*i)
  return r
print(qqq(sum))

5
55


Q21.Can we write every loop as list comprehension in Python?
* Yes, sort of. You can convert nested for loops to list comprehensions, and even use variable assignment with :=
* Every list comprehension can be rewritten as a for loop but not every for loop can be rewritten as a list comprehension 

In [ ]:
# Q4. Write a python program to find uncommon words from a string.
def UncommonWords(A, B):
   count = {} 
   for word in A.split(): 
     count[word] = count.get(word, 0) + 1
   for word in B.split(): 
        count[word] = count.get(word, 0) + 1
   return [word for word in count if count[word] == 1]
A = "Almabetter" B = "Learning from Almabe

print(UncommonWords(A, B))



IndentationError: ignored

In [ ]:
A = input("Enter first string:")
B = input("Enter secoud string:")

def UncommonWords(A, B):
  count = {}
  for word in A.split():
    count[word] = count.get(word, 0) +1
  for word in B.split():
    count[word] = count.get(word,0) + 1
  return [ word for word in count if count[word] == 1]
print(UncommonWords(A,B))

Enter first string:sumit
Enter secoud string:sumit gaikwad
['gaikwad']


In [ ]:
A = input()
B = input()
def uncomword(A,B):
  count = {}
  for x in A.split():
    count[x] = count.get(x,0) +1
  for x in B.split():
    count[x] = count.get(x,0) + 1
  return [x for x in count if count[x] == 1]
print(uncomword(A,B))


sumit
sumit gaikwad
['gaikwad']


In [ ]:
#Q2. Write a python program to replace multiple words in a string with a word if, given set of words are found in string.
 
test_str = 'AlmaBetter is best for geeks and CS' 
print("The original string is : " + str(test_str)) 
word_list = ["best", 'CS', 'for']
 repl_wrd = 'gfg'
 res = ' '.join([repl_wrd if idx in word_list else idx for idx in test_str.split()])
 print("String after multiple replace : " + str(res))

In [ ]:
test_str = 'AlmaBetter is best for geeks and CS'
print("The original string is : " + str(test_str)) 
word_list = ["best", 'CS', 'for']
repl_wrd = 'gfg'
res = ' '.join([repl_wrd if idx in word_list else idx for idx in test_str.split()])
print("String after multiple replace : " + str(res))




The original string is : AlmaBetter is best for geeks and CS
String after multiple replace : AlmaBetter is gfg gfg geeks and gfg


In [ ]:
# remove duplicte useing def funtion
def removedupl(lis):
  return list(set(lis))

In [ ]:
L = [1,2,31,4,3,2,1,4,2,3]
print(removedupl(L))

question github

In [ ]:
# write a python progarm to count the number of characters ( chatacter frequency) in string

In [ ]:
str = input()
y = {}
for x in str.lower():
  if x in y:
    y[x] +=1
  else:
    y[x] = 1
print(y)

sumit rameshawar gaikwad
{'s': 2, 'u': 1, 'm': 2, 'i': 2, 't': 1, ' ': 2, 'r': 2, 'a': 5, 'e': 1, 'h': 1, 'w': 2, 'g': 1, 'k': 1, 'd': 1}


In [ ]:
x = input()
y = {}
for x in x.lower():
  if x in y:
    y[x] += 1
  else:
    y[x] = 1
print(y)

Sumit Rameshwar Gaikwad
{'s': 2, 'u': 1, 'm': 2, 'i': 2, 't': 1, ' ': 2, 'r': 2, 'a': 4, 'e': 1, 'h': 1, 'w': 2, 'g': 1, 'k': 1, 'd': 1}


In [ ]:
sss = input("Enter u r string:" )
y = {}
for x in sss.lower():
  if x in y:
    y[x] += 1
  else:
    y[x] = 1
print(y) 

Enter u r string:Sumit Gaikwad
{'s': 1, 'u': 1, 'm': 1, 'i': 2, 't': 1, ' ': 1, 'g': 1, 'a': 2, 'k': 1, 'w': 1, 'd': 1}


In [ ]:
strng = input()
dic = dict()
l = []
for i in strng.lower():
  l.append(i)


s = []
for k in range(len(strng)):
  s.append(l.count(l[k]))

l5 = list(zip(l,s))
dict(l5)

Sumit Rameshawar Gaikwad


{'s': 2,
 'u': 1,
 'm': 2,
 'i': 2,
 't': 1,
 ' ': 2,
 'r': 2,
 'a': 5,
 'e': 1,
 'h': 1,
 'w': 2,
 'g': 1,
 'k': 1,
 'd': 1}

In [ ]:
# Q.Write a function which calculates the mode of a list of numbers. If there are two modes in the dataset, it should return both.

In [ ]:
# Find mode with count: only one mode occuring first
# packages
from scipy import stats as st
import numpy as np

# creating an array using array() method
l = np.array([1,2,3,4,5,5,5,4,3,2,1,2,0])

# applying mode operation on array and
# printing result
print(st.mode(l))

ModeResult(mode=array([2]), count=array([3]))


In [ ]:
def mode(ls):
    # dictionary to keep count of each value
    counts = {}
    # iterate through the list
    for item in ls:
        if item in counts:
            counts[item] += 1
        else:
            counts[item] = 1
    # get the keys with the max counts
    return [key for key in counts.keys() if counts[key] == max(counts.values())]

# use the function on a list of values
mode([1,2,3,4,5,5,5,4,3,2,1,2,0])


[2, 5]

In [ ]:
def mode(L):
  count = {}
  for i in L:
    if i in count:
      count[i] += 1
    else:
      count[i] = 1
  return [ key for key in count.keys() if count[key] == max(count.values())]
mode([1,2,3,4,5,5,5,4,3,2,1,2,0])


[2, 5]

In [ ]:
# Q.The included code stub will read an integer, , from STDIN.

#Without using any string methods, try to print the following:

#12345...n

#Note that "" represents the consecutive values in between.

#Example n = 5

#Print the string 12345.
n = int(input())
for i in range(1,n+1):
  print(i, end = "")
     

6
123456

In [ ]:
# Q.Consider a series 1+ 2+ 3+ 4+ 5 +..., ge the value of n from the userprint addition of the first n natural numbers whithout using loops and by using loops
# loop
n = int(input('number: '))
sum = 0
for i in range (1, n+1):
  sum = sum +i
print(sum)

number: 5
15


In [ ]:
# Q.create a program to get a string from user and checks that is palindrome or not.

x = input('string:')
if x[::-1] == x[::] :
  print('x is polindrome')
else:
  print(' x is not polindome')

string:ssuuss
x is polindrome


In [ ]:
po = input('string:')
if po[::-1] == po[::]:
  print(' its polindrome')
else:
  print('Not polindome')

string:susus
 its polindrome


<B> Q **100** python question

```



In [ ]:
# 1.User will input (3ages).Find the oldest one

a = int(input('enter the first age'))
b = int(input('enter the second age'))
c = int(input('enter the third age'))
max = a
if max < b:
  max= b
if max < c:
  max = c
print('oldest one:', max)

enter the first age25
enter the second age48
enter the third age45
oldest one: 48


In [ ]:
# 2.2.Write a program that will convert celsius value to fahrenheit
temp = float(input('Enter temp in celcius'))
fahrenheit = (temp *1.8)+32
print(fahrenheit)

Enter temp in celcius56
132.8


In [ ]:
# 3.3.User will input (2numbers).Write a program to swap the numbers
a = int(input('enter first num'))
b = int(input('enter second num'))
# swaping
c = a
a = b
b = c
print('value of a:',a)
print('value of b:',b)


enter first num5
enter second num10
value of a: 10
value of b: 5


In [ ]:
#4.Write a program that will give you the sum of 3 digits

num = int(input('Enter three digit number'))

a = num % 10 #(123 % 10 = 3)
num = num//10 #(123//10 =12)
b = num % 10 #(12%10=2)
c = num//10 # (12//10=1)

rev = (a+b+c)
print(rev)





Enter three digit number123
6


In [ ]:
# 5.Write a program that will reverse a four digit number.Also it checks whether the reverse is true.
# user input

user_input = int(input('Enter the four digits num'))
num = user_input
# digits
a = num % 10
num = num//10

b = num % 10
num = num//10

c= num % 10
d = num//10

# formula
rev = 1000*a + 100*b + 10*c + d
print('orginal num-',user_input)
print('reverse num-',rev)
#check
if user_input == rev:
  print('True')
else:
  print('False')


Enter the four digits num1234
orginal num- 1234
reverse num- 4321
False


In [ ]:
# 6.Write a program that will tell whether the number entered by the user is odd or even.
x = int(input('Enter your num'))

if x % 2 == 0:
  print('even')
else:
  print('old')

Enter your num7
old


In [ ]:
#7.Write a program that will tell whether the given year is a leap year or not.
year = int(input('Enter the year'))

if year % 4 == 0:
  print('leap year')
else:
  print('not leap year')



Enter the year1997
not leap year


In [ ]:
#8.Write a program to find the euclidean distance between two coordinates.
x_1 = float(input('Enter x1 of x coordinate'))
y_1 = float(input('Enter y1 of y coordinate'))
x_2 = float(input('Enter x2 of x coordinate'))
y_2 = float(input('Enter y2 of y coordinate'))

d = ((x_2 - x_1)**2 + (y_2 - y_1)**2)**0.5
print(d)

Enter x1 of x coordinate55
Enter y1 of y coordinate44
Enter x2 of x coordinate66
Enter y2 of y coordinate77
34.785054261852174


In [ ]:
#9.Write a program that take a user inputr of three angles and will find out whether it can form a triangle or not.
a = int(input('Enter your frist angle:'))
b = int(input('Enter your second angle:'))
c = int(input('Enter your third angle:'))

if a + b + c == 180 and a!=0 and b!=0 and c!=0:
   print('yes')
else:
  print('Not')


Enter your frist angle:90
Enter your second angle:45
Enter your third angle:45
yes


In [ ]:
#10.Write a program that will take user input of cost price and selling price and determines whether its a loss or a profit

cp = float(input('Enter your cost price:'))
sp = float(input('Enter your selling price'))

if cp > sp:
  amt = cp - sp
  print('Loss:',amt)
else:
  amt = sp -cp
  print('Profit:',amt)

Enter your cost price:150
Enter your selling price180
Profit: 30.0


In [ ]:
# 11.Write a program to find the simple interest when the value of principle,rate of interest and time period is given.

p= int(input('Enter your principal'))
r = int(input('Enter your rate of interest'))
t = int(input('Enter your time period in years'))

si = (p * r * t)/100
print('simple Interst:',si)
a = p +si
print('Amount is:',a)

Enter your principal250000
Enter your rate of interest12
Enter your time period in years5
simple Interst: 150000.0
Amount is: 400000.0


In [ ]:
#12.Write a program to find the volume of the cylinder. Also find the cost when ,when the cost of 1litre milk is 40Rs.

r = float(input('Enter your radius:'))
h = float(input('Enter your height:'))

v = 3.14*(r**2)*h
print('Volume is:',v)
cost = v/1000*40
print('cost is:','Rs',cost)

Enter your radius:4
Enter your height:7
Volume is: 351.68
cost is: Rs 14.0672


In [ ]:
# 13.Write  a program that will tell whether the given number is divisible by 3 & 6.

num = int(input('Enter your number:'))

if num % 3 == 0 and num % 6 ==0:
  print(num,'is divisiable by 3 and 6')
else:
  print(num,'not divisible by 3 and 6')


Enter your number:17
17 not divisible by 3 and 6


In [ ]:
#16.Write a program that will determine weather when the value of temperature and humidity is provided by the user.
TEMPERATURE(C)      HUMIDITY(%)      WEATHER

      >= 30                             >=90                Hot and Humid
      >= 30                             < 90                 Hot
      <30                                >= 90               Cool and Humid
      <30                                 <90                 Cool

In [ ]:
temp = int(input('Enter temp is celcius:'))
humid = int(input('Enter humidity percentage'))

if temp >=30 and humid >=90:
  print('Hot and Humid')
elif temp >=30 and humid <90:
  print('Hot')
elif temp <30 and humid >=90:
  print('Cold and Humid')
else:
  print('Cold')

Enter temp is celcius:30
Enter humidity percentage90
Hot and Humid


In [ ]:
# 17.Write a program that will take three digits from the user and add the square of each digit.
# 1+4+25=30
num = int(input('Enter your number'))
a = num % 10
num = num//10
b = num % 10
c = num//10

add = (a**2) +(b**2) + ( c**2)
print('adding square digits is :',add)


Enter your number125
adding square digits is : 30


In [ ]:
# 18.Write a program that will check whether the number is armstrong number or not.
# 153
# (1**3)+(5**3)+(3**3) = 1+125+27=153

user_input = int(input('Enter your number:'))
num = user_input

a = num % 10
num = num //10
b = num % 10
c = num//10

if (a**3) +(b**3)+(c**3) == user_input:
  print('Armstrong number')
else:
  print('Not an Armstorng Number')



Enter your number:153
Armstrong number


In [ ]:
u_input= int(input('Enter num:'))
num = u_input

a = num % 10
num = num //10
b = num % 10
c = num // 10

if (a**3) + (b**3) + (c**3) == u_input:
  print('am')
else:
  print('not')

Enter num:153
am


In [ ]:
# 19.Write a program that will take user input of (4 digits number) and check whether the number is narcissist number or not.

user_input = int(input('Enter a four digits number'))
num = user_input

a = num % 10
num = num //10
b = num % 10
num = num //10
c = num%10
d = num //10

if (a**4) +(b**4)+(c**4)+(d**4) == user_input:
  print('narcissist number:')
else:
  print('Not a Narcissictic number:')
 


Enter a four digits number8208
narcissist number:


In [ ]:
# 20.Write a program that will give you the in hand salary after deduction of HRA(10%),DA(5%),PF(3%), and tax(if salary is between 5-10 lakh–10%),(11-20lakh–20%),(20< _   – 30%)(0-1lakh print k).

user_input = float(input('Enter annual salary'))

if user_input > 500000 and user_input < 1000000:
  tax = (10/100)*usre_input
  temp_salary = user_input - tax
elif user_input > 1000000 and user_input <200000:
  tax = (20/100)*user_input
  temp_salary = user_input
else:
  tax = (30/100)*user_input
  temp_salary = user_input - tax

print('After salary reduction:',temp_salary)

hra = (10/100)*temp_salary
da = (5/100)*temp_salary
pf = (3/100)*temp_salary

In_handsalary = (temp_salary - hra -da -pf)/12
print('In Hand salary is :',In_handsalary)

if In_handsalary <= 999:
  print(In_handsalary)
elif In_handsalary >= 1000 and In_handsalary <=9999:
  print(In_handsalary/1000,'k')
elif In_handsalary >=100000 and In_handsalary <=99999999:
  print(In_handsalary/1000000,'l')
else:
  print(In_handsalary/10000000,'Cr')



Enter annual salary1600000
After salary reduction: 1120000.0
In Hand salary is : 76533.33333333333
0.007653333333333333 Cr


In [ ]:
#21.Write a menu driven program - 1.cm to ft  2.kl to miles  3.usd to inr  4.exit

user_input = input(''' Hi welcome to my page
what would you like bto do?

1.Convert cm to inches
2. Convert km to miles
3. Convert usd to inr
4.Exit ''')

if user_input == '1':
  cm = float(input('Enter value in cm'))
  inch = cm * 0.349
  print('value in inch is-',inch)
elif user_input == '2':
  km = float(input('Enter value in km'))
  mile = km * 0.621
  print('value in miles is-',mile)
elif user_input == '3':
  usd = float(input('Enter value in usd'))
  inr = usd * 76.63
  print('value in inr is',inr)
else:
  print('Exit')

 Hi welcome to my page
what would you like bto do?

1.Convert cm to inches
2. Convert km to miles
3. Convert usd to inr
4.Exit 2
Enter value in km5
value in miles is- 3.105


In [ ]:
# 22.Write a program that will tell the number of dogs and chicken are there when the user will provide the value of total heads and legs.


In [ ]:
# 23.23.Write a program that will swap numbers

a = int(input('Enter frist number'))
b = int(input('Enter second number'))

a = a + b
b = a - b
a = a - b
print('After swapping:')
print(' a is:',a)
print(' b is:',b)


Enter frist number5
Enter second number10
After swapping:
 a is: 10
 b is: 5


In [ ]:
# 24 24.Write a program to find the sum of first n numbers, where n will be provided by the user. Eg if the user provides n=10 the output should be 55.

n = int(input('Enter number:'))
s = n *(n + 1)/2
print('Sum is :',s)

Enter number:5
Sum is : 15.0


In [ ]:
#25.Write a program that can multiply 2 numbers provided by the user without using the * operator

first_num = int(input('frist num:'))
sec_num = int(input('second num:'))
sum = 0
for i in range(0,first_num):
  sum = sum + sec_num
print('result is :',sum)


frist num:5
second num:10
result is : 50


In [ ]:
# 26.Write a program that can find the factorial of a given number provided by the user.

num = int(input('Enter number'))

i = 1
if num > 0:
  while num >= 1:
    i = i * num
    num = num - 1
  print('Factorial of the given number is :',i)
else:
  print(' Not possiable')



Enter number5
Factorial of the given number is : 120


In [ ]:
#27.Write a program to print the first 25 odd numbers

flag = 0 
i = 1
while True:
  if i % 2 != 0:
    print(i)
    flag = flag + 1
  if flag == 25:
    break
  i = i +1

1
3
5
7
9
11
13
15
17
19
21
23
25
27
29
31
33
35
37
39
41
43
45
47
49


In [ ]:
#28.Write a program to print whether a given number is prime number or not

num = int(input('Enter number'))

if num == 2:
  print('Prime number')
elif num > 1:
  for i in range(2,num):
    if (num % i) == 0:
      print(num,"is not prime n number")
      break
    else:
      print(num,'is a prime number')
      break
  else:
    print(num,"is not prime number")

Enter number25
25 is a prime number


In [ ]:
# 29.Print all the armstrong numbers in the range of 100 to 1000
for num in range(100,1000):

  i=num
  a = num % 10
  num = num // 10
  b = num % 10
  c = num // 10

  if (a**3) +(b**3) +(c**3) == i:
      print(i)
  i = i + 1


153
370
371
407


In [ ]:
# 30.The current population of a town is 10000. The population of the town is increasing at the rate of 10% per year. You have to write a program to find out the population at the end of each of the last 10 years. For eg current population is 10000 so the output should be like this:
10th year - 10000
9th year - 9000
8th year - 8100 and so on

In [ ]:
flag = 0
a = 10000
print(a)

while True:
  b = (a) - ((10*a)/100)
  a = b
  print(int(b))
  flag = flag + 1

  if flag == 9:
    break


10000
9000
8100
7290
6561
5904
5314
4782
4304
3874


In [ ]:
# 31.Write a program to print all the unique combinations of 1,2,3 and 4

for i in range(1,5):
  for j in range (1,5):
    if(i != j):
      print(i,j)


1 2
1 3
1 4
2 1
2 3
2 4
3 1
3 2
3 4
4 1
4 2
4 3


In [ ]:
# 32.User will provide 2 numbers you have to find the HCF of those 2 numbers

a = int(input('Enter the first number:'))
b = int(input('Enter the second number:'))

while a % b != 0:
  rem = a % b
  a = b
  b = rem
print('your HcF is:',b)

Enter the first number:8
Enter the second number:9
your HcF is: 1


In [ ]:
# 33.User will provide 2 numbers you have to find the by LCM of those 2 numbers

a = int(input('Enter the first number:'))
num_1 = a
b = int(input('Enter the second number:'))
num_2 = b

while num_1 % num_2 != 0:
  rem = num_1 % num_2
  num_1 = num_2
  num_2 = rem
hcf = num_2

lcm = (a * b)/hcf
print('LCM is:',lcm)


Enter the first number:22
Enter the second number:12
LCM is: 132.0


In [ ]:
# 34.Print first 25 prime numbers

counter = 0
num = 2
while(counter <= 25):
  for i in range(2,num):
    if num % i == 0:
      break
  else:
    print(num)
    counter = counter + 1
  num = num +1


2
3
5
7
11
13
17
19
23
29
31
37
41
43
47
53
59
61
67
71
73
79
83
89
97
101


In [ ]:
# 35.Print the first 20 numbers of a Fibonacci series

count = 0
a = 0
b = 1
print(a)
print(b)

while True:
  c = a + b
  a = b
  b = c
  print(c)
  count = count + 1
  if count == 18 :
    break

0
1
1
2
3
5
8
13
21
34
55
89
144
233
377
610
987
1597
2584
4181


In [ ]:
#36.Write a program to find the compound interest 

p = int(input('Enter Pricipal:'))
r = int(input('Enter Rate of interest:'))
t = int(input('Enter the time period elapsed:'))

a = p*(1+r/100)**t
print('amount is:',a)

ci = a -p
print('compound interest is :',ci)


Enter Pricipal:50000
Enter Rate of interest:12
Enter the time period elapsed:1
amount is: 56000.00000000001
compound interest is : 6000.000000000007


In [ ]:
#37.Write a Python program that accepts an integer (n) and computes the value of n+nn+nnn.
# n+ nn+ nnn

n = input('Enter number')
print('n is:',n)
nn = n+n
print('nn is:',nn)
nnn = n+n+n
print('nnn is:',nnn)
c = int(n) + int(nn) + int(nnn)
print(c)


Enter number5
n is: 5
nn is: 55
nnn is: 555
615


In [ ]:
#38.Take a number from the user and find the number of digits in it. 

a = int(input('Enter number:'))
count = 0

while(a > 0):
  a = a // 10
  count = count + 1
print('Number of digits:',count)

Enter number:12456328794236412654
Number of digits: 20


In [ ]:
# 39.Print all factors of a given number provided by the user.

num = int(input('Enter number:'))

for i in range(1,num + 1):
  if num % i == 0:
    print('factors are:',i)


Enter number:56
factors are: 1
factors are: 2
factors are: 4
factors are: 7
factors are: 8
factors are: 14
factors are: 28
factors are: 56


In [ ]:
# 40.Find the reverse of a number provided by the user(any number of digit) 

a = int(input('Enter number:'))
rev = 0

while a > 0:
  rem = a % 10
  a = a // 10
  rev = (rev * 10) +(rem)
print('reversed value:',rev)

Enter number:12345
reversed value: 54321


In [ ]:
#46.Write a program to calculate the sum of the following series till the nth term
#1/1! + 2/2! + 3/3! + 4/4! +…….+ n/n!
#n will be provided by the user

num = int(input('Enter number:'))
result = 0
fact = 1

for i in range(1,num + 1):
  fact = fact * i
  result = result + (i/fact)
print(result)






Enter number:5
2.708333333333333


In [ ]:
from traitlets.config.application import T
#49. Write a program that keeps on accepting a number from the user until the user enters Zero. Display the sum and average of all the numbers.

num = int(input('Enter number'))
add = 0
avg = 0
count = 0

while True:
  if num != 0:
    add = add + num
    count = count + 1
    avg = add/count
    num = int(input('Another number please:'))

  else:
    print("txn")
    break
print('sum is:',add)
print('averge:',avg)



Enter number5
Another number please:7
Another number please:2
Another number please:0
txn
sum is: 14
averge: 4.666666666666667


In [ ]:
#51.Find the length of a given string without using the len() function. 

a = input("Enter string")
count = 0
for i in a:
  count = count +1
print('Length of string is:',count)

Enter stringSumit rameshwar gaikwad
Length of string is: 23


In [ ]:
#52.Extract username from a given email. 
#Eg if the email is nitish24singh@gmail.com then the username should be nitish24singh

email = input('Enter email')
username,mail = email.split('@')
print(username)


Enter emailgaikwads070@gmail.com
gaikwads070


In [ ]:
#53.Count the frequency of a particular character in a provided string. Eg 'hello how are you' is the string, the frequency of h in this string is 2.

a = input('Enter string')
b = input('Enter charachetr')
count = 0

for i in a:
  if i in b:
    count = count +1
print('Character occurred:',count,'times')


Enter stringhello sumit gaikwad
Enter charachetra
Character occurred: 2 times


In [ ]:
#54.Find the index position of a particular character in another string. 

a = input('Enter string:')
b = input('enter charachter:')
print(a.index(b))

Enter string: i am sumit gaikwad
enter charachter:g
12


In [ ]:
#55.Count the number of vowels in a string provided by the user.
a = input('entr u string')
vowels = 'aeiou'
count = 0

for i in a:
  if i in vowels:
    count = count + 1
print(count)

entr u stringsumit gaikwad
5


In [ ]:
#56.Write a program which can remove a particular character from a string. 

a = input(" Enter u string")
b = int(input(" Enter value of character"))
#
c = a[0:b-1]
d = a[b:]
print(c+d)

 Enter u stringsumit
 Enter value of character4
sumt


In [ ]:
#57.Write a program that can check whether a given string is palindrome or not.

a = input("Enter u string")
rev = ''

for i in range(len(a)-1,-1,-1):
  rev = rev + a[i]
print(rev)
if rev == a:
  print('palindrome')
else:
  print('Not palindrome')


Enter u stringdontnod
dontnod
palindrome


In [ ]:
#58.Write a python program to remove all the duplicates from a list
l1 = [1,5,4,2,2,7,8,5]
l2 = []

for i in l1:
  if i not in l2:
    l2.append(i)
print(l2)

[1, 5, 4, 2, 7, 8]


In [ ]:
#59.Write a python program to convert a string to title case without using the title()

a = ' hello sumit gaikwad'
y = a.split()
print(y)
r = ''
for i in y:
  r = r + i[0].upper() + i[1:].lower() + ' '
print(r) 


['hello', 'sumit', 'gaikwad']
Hello Sumit Gaikwad 


In [ ]:
#60.Write a python program to find the max item from a list without using the max function

L = [2,3,4,5,6,7,8,9]
max = L[0]
for i in L:
  if i > max:
    max = i
print(max)


9


In [ ]:
#61.Write a python program to reverse a list

L = [1,45,2,4,3,4,8,2]
rev = []

for i in range(len(L)-1,-1,-1):
  rev.append(L[i])
print(rev)

[2, 8, 4, 3, 4, 2, 45, 1]


In [ ]:
# 62.Write a python program to search a given number from a list

L = [1,2,3,4,5,6,7,8,9]
num = int(input("Enter number"))

for i in L:
  if i == num:
    print('True')
    break
else:
  print('False')

Enter number5
True


In [ ]:
#63.Write a program that can create a new list from a given list where each item in the new list is square of the item of the old list

l1 = [2,4,5,6,7]
l2 = []
for i in l1:
  l2.append(i**2)
print(l2)



[4, 16, 25, 36, 49]


In [ ]:
#64.Write a program that can reverse words of a given string.

a = input('Enter string')
x = a.split()
rev = []

for i in range(len(x)-1,-1,-1):
  rev.append(x[i])
y = ' '.join(rev)
print(y)

Enter stringsumit gaikwad
gaikwad sumit


In [ ]:
#65.Write a program that can count the number of words in a given string

a = input('Entr string')
count = 0

for i in a:
  if i == ' ':
    count = count +1
words = count + 1
print('Number of words in string:',words)



Entr stringsumit gaikwad
Number of words in string: 2


In [ ]:
#66.Write a program to check if a list is in ascending order or not

L = [1,2,3,45,6]
flag = 0

for i in range(0,len(L)-1):
  if L[i] >= L[i + 1]:
    flag = 1
    break
if flag == 0:
  print('Sorted')
else:
  print('Not sorted')



Not sorted


In [ ]:
# 67.Create 2 lists from a given list where 1st list will contain all the odd numbers from the original list and the 2nd one will contain all the even numbers 

L = [1,2,3,4,5,6,7,8,9]
L_even = []
L_odd = []

for i in L:
  if i % 2 == 0:
    L_even.append(i)
  else:
    L_odd.append(i)
print('List of even numbers:',L_even)
print('List of odd numbers:',L_odd)



List of even numbers: [2, 4, 6, 8]
List of odd numbers: [1, 3, 5, 7, 9]


In [ ]:
# 68.Write a program to merge 2 list without using the + operator
L1 = [1,2,3,4]
L2 = [5,6,7,8,9]
L = []

for i in L1:
  L.append(i)
for j in L2:
  L.append(j)
print(L)



[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [ ]:
# 69.Write a program to replace an item with a different item if found in the list 

L = [1,2,3,4,5]
find = int(input('Enter the number for replace'))
replace = int(input('Enter number'))

for i in range(0,len(L)):
  if find == L[i]:
    L[i] = replace
    print(L)
    break
else:
  print('Not found')


Enter the number for replace3
Enter number7
[1, 2, 7, 4, 5]


In [ ]:
#70.Write a program that can convert a 2D list to 1D listWrite a program that can print 
L = [1,2,3,4,[5,6,7,8]]
rev = []

for i in L:
  if type(i)==list:
    rev.extend(i)
  else:
    rev.append(i)
 
print(rev)




[1, 2, 3, 4, 5, 6, 7, 8]


In [ ]:
# 71.Write a program that can perform union and intersection on 2 given list. 

L1 = [1,2,3,4,5]
L2 = [3,4,5,6,7]
# union
Union = []
intersection = []

for i in L1:
  if i not in Union:
    Union.append(i)
for j in L2:
  if j not in Union:
    Union.append(j)
# intersection
for i in L1:
  if i in L2:
    intersection.append(i)
print('Union list:',Union)
print('intersection:',intersection)


Union list: [1, 2, 3, 4, 5, 6, 7]
intersection: [3, 4, 5]


In [ ]:
#72.the max item of each row of a matrix. 

matrix = [
    [1,2,3],
    [8,5,6],
    [7,8,9]
]
for i in matrix:
  max = i[0]
  for j in i:
    if j > max:
      max = j
  print(max)    




3
8
9


In [ ]:
#74.Write a program to print the shape of a matrix. 

matrix = [
    [1,2,3],
    [4,5,6]
]
row = 0
for i in matrix:
  row = row + 1
print('the shape of this matrix is:',row,'*', len(i))

the shape of this matrix is: 2 * 3


In [ ]:
#75.Write a program that can check if you can perform matrix multiplication on 2 matrices 

matrix_1 = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]
row_1 = 0
for i in matrix_1:
  row_1 = row_1 +1
  column_1 = len(i)
  print('matrix_1:',i)
print('Row_1:',row_1)
print('Column_1:',column_1) 

matrix_2 = [
    [2,3],
    [4,5],
    [7,8]
]
row_2 = 0
for j in matrix_2:
  row_2 = row_2 +1
  column_2 = len(j)
  print('matrix_2:',j)
print('Row_2:',row_2)
print('Column_2:',column_2)

if column_1 == row_2:
  print('Multipilcation is possible')
else:
  print('Not possiable')


matrix_1: [1, 2, 3]
matrix_1: [4, 5, 6]
matrix_1: [7, 8, 9]
Row_1: 3
Column_1: 3
matrix_2: [2, 3]
matrix_2: [4, 5]
matrix_2: [7, 8]
Row_2: 3
Column_2: 2
Multipilcation is possible


In [ ]:
#77.Write a program that can sort a given unsorted list. Dont use any built in function for sorting.

L = [5,3,4,8,6,5,8]

for i in range(len(L)):
  for k in range(0,len(L)-1):
    if L[k]>L[k+1]:
      temp = L[k]
      L[k] = L[k+1]
      L[k+1] = temp
print(L)

[3, 4, 5, 5, 6, 8, 8]


In [ ]:
L = [5,3,4,8,6,5,8]
L.sort()
print(L)

[3, 4, 5, 5, 6, 8, 8]


In [ ]:
#87.Write a function that accepts a number and returns it’s factorial. You can not use any loop

A= int(input("Enter number"))
def fact(num):
  if num == 1:
    return 1
  else:
    return num * fact(num-1)
print(fact(A))


Enter number6
720


In [ ]:
#84.Write a function that accepts a list of strings and performs Bag of words and convert it to numerical vectors.
 

In [ ]:
#86.Write a program that accepts neighbors(set of 2D co-ordinates) and a point(single 2D co-ordinate) and tells nearest neighbor(in terms of euclidean distance)




In [ ]:
#83.Write a function that accepts a string and returns the number of upper case chars and lower case chars as a dictionary

a = input('Enter string:')
D = {}
upper_count = 0
lower_count = 0

for i in a:
  if (i.isupper()):
    upper_count = upper_count + 1
  elif (i.islower()):
    lower_count = lower_count + 1
D = {'upper case':upper_count,'Lower case':lower_count}
print(D)


Enter string:My Name is Sumit Gaikwad
{'upper case': 4, 'Lower case': 16}


In [ ]:
#79.Assume a list with numbers from 1 to 10 and then convert it into a dictionary where the key would be the numbers of the list and the values would be the square of those numbers.

L = [1,2,3,4,5,6,7,8,9]
D = {}

for i in L:
  D[i] = i**2
print(D)

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81}


In [ ]:
#80.Write a program to merge two given dictionary

D1 = {'a':2,'b':3}
D2 = {'c':4,'d':5}
D = {}

for i in D1:
  D[i]=D1[i]
for k in D2:
  D[k] = D2[k]
print(D)




{'a': 2, 'b': 3, 'c': 4, 'd': 5}


In [5]:
#Please ensure the platform IDE is in Python 3.x mode.
#If you face any issue here, you may write the code on colab or jupyter. 
#Then, paste the code snippet here and run test cases.

num = int(input())
def palindrome(num):
    if str (num[::-1]) == str (num[::]):
        return "ture"
    else:
        return "false"
print(palindrome(num))

112211


TypeError: ignored

In [6]:
def is_palindrome(num):
    return str(num) == str(num)[::-1]

# example usage
print(is_palindrome(121)) # Output: True
print(is_palindrome(123)) # Output: False


True
False


In [8]:
#Sum of even and odd numbers
#Easy
#Write a program to input an integer N and print the sum of all its even digits and sum of all its odd digits separately.
def sum_of_even_and_odd_digits(n):
    even_sum = 0
    odd_sum = 0
    for digit in str(n):
        digit = int(digit)
        if digit % 2 == 0:
            even_sum += digit
        else:
            odd_sum += digit
    return even_sum, odd_sum

# example usage
print(sum_of_even_and_odd_digits(123456789)) 


(20, 25)


In [14]:
if __name__ == '__main__':
    a = int(input())
    b = int(input())
    a=4
    b=3
    print(a//b)
    print(a/b)


4
3
1
1.3333333333333333


In [17]:
 a=4
 b=3
print(a//b)
print(a/b)


1
1.3333333333333333


In [21]:
if __name__ == '__main__':
    n = int(input())
    if i in (n*2):
      print(n)


5


NameError: ignored

In [ ]:
A=input()
def rev_str(A):
  return A[::-1].lower()
print(rev_str(A))

Sumit
timus


In [ ]:
A = input()
def removesapce(A):
  return (A.replace(" ",""))
print(removespace(A))